CREATE TYPE "reservation_status" AS ENUM (
  'PENDING',
  'APPROVED',
  'CHECKED_OUT',
  'COMPLETED',
  'CANCELLED',
  'DENIED'
);

CREATE TYPE "code_types" AS ENUM (
  'BARCODE',
  'QR',
  'NFC'
);

CREATE TYPE "property_data_type" AS ENUM (
  'VARCHAR',
  'INTEGER',
  'DECIMAL',
  'REAL',
  'BOOLEAN',
  'TIMESTAMP',
  'DATE'
);

CREATE TYPE "iso_currency_codes" AS ENUM (
  'USD',
  'CAD',
  'MEX'
);

CREATE TYPE "file_categories" AS ENUM (
  'Archive',
  'Document',
  'Spreadsheet',
  'Presentation',
  'Image',
  'Video',
  'Audio'
);

CREATE TYPE "file_types" AS ENUM (
  'JPEG',
  'PNG',
  'GIF',
  'BMP',
  'TIFF',
  'PDF',
  'DOC',
  'DOCX',
  'TXT',
  'RTF',
  'CSV',
  'XLS',
  'XLSX',
  'PPT',
  'PPTX',
  'ZIP',
  'RAR',
  '7Z',
  'MP3',
  'WAV',
  'MP4',
  'AVI',
  'MKV',
  'SVG'
);

CREATE TYPE "email_type" AS ENUM (
  'work',
  'personal',
  'business'
);

CREATE TYPE "phone_type" AS ENUM (
  'mobile',
  'work',
  'home'
);

CREATE TYPE "attachment_type" AS ENUM (
  'profile_pic',
  'hero_pic',
  'thumbnail',
  'document_cover',
  'avatar',
  'banner',
  'logo',
  'background',
  'icon',
  'miscellaneous'
);

CREATE TYPE "image_size" AS ENUM (
  'original',
  'x',
  'small',
  'medium',
  'large',
  'xlarge'
);

CREATE TYPE "address_type" AS ENUM (
  'home',
  'business',
  'other'
);

CREATE TYPE "iso_country_codes" AS ENUM (
  'US',
  'CA',
  'MX'
);

CREATE TYPE "timezones" AS ENUM (
  'America/New_York',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'America/Phoenix',
  'America/Anchorage',
  'America/Juneau',
  'America/Honolulu'
);

CREATE TYPE "state_codes" AS ENUM (
  'AL',
  'AK',
  'AZ',
  'AR',
  'CA',
  'CO',
  'CT',
  'DE',
  'FL',
  'GA',
  'HI',
  'ID',
  'IL',
  'IN',
  'IA',
  'KS',
  'KY',
  'LA',
  'ME',
  'MD',
  'MA',
  'MI',
  'MN',
  'MS',
  'MO',
  'MT',
  'NE',
  'NV',
  'NH',
  'NJ',
  'NM',
  'NY',
  'NC',
  'ND',
  'OH',
  'OK',
  'OR',
  'PA',
  'RI',
  'SC',
  'SD',
  'TN',
  'TX',
  'UT',
  'VT',
  'VA',
  'WA',
  'WV',
  'WI',
  'WY'
);

CREATE TYPE "state_names" AS ENUM (
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming'
);

CREATE TABLE "global_settings" (
  "id" varchar(64) PRIMARY KEY,
  "default_currency_id" smallint,
  "time_format_is_24h" bool,
  "audit_info_id" int
);

CREATE TABLE "audit_info" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "operation_type" enum,
  "details" text,
  "created_by" int,
  "created_at" timestamp DEFAULT (current_timestamp),
  "last_edited_by" int,
  "last_edited_at" timestamp DEFAULT (current_timestamp),
  "is_archived" bool,
  "archived_at" timestamp
);

CREATE TABLE "reservations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reserved_for" int,
  "area_id" int,
  "planned_checkout_time" timestamp,
  "planned_checkin_time" timestamp,
  "checkout_time" timestamp,
  "checkin_time" timestamp,
  "is_indefinite" bool DEFAULT (false),
  "audit_info_id" int
);

CREATE TABLE "reservation_assets" (
  "reservation_id" int,
  "asset_id" int,
  "audit_info_id" int
);

CREATE TABLE "scan_tags" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "asset_id" int,
  "code_data" varchar,
  "code_type" code_types,
  "audit_info_id" int
);

CREATE TABLE "comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parent_comment_id" int,
  "related_entity_type" varchar,
  "related_entity_id" int,
  "comment" text,
  "audit_info_id" int
);

CREATE TABLE "reactions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "comment_id" int NOT NULL,
  "reaction_type" varchar NOT NULL,
  "audit_info_id" int
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parent_category_id" int,
  "name" varchar,
  "audit_info_id" int
);

CREATE TABLE "custom_properties" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "value" varchar,
  "data_type" property_data_type,
  "audit_info_id" int
);

CREATE TABLE "asset_custom_properties" (
  "asset_id" int,
  "property_id" int,
  "value" varchar,
  "audit_info_id" int
);

CREATE TABLE "assets" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "manufacturer" varchar,
  "model_number" varchar,
  "model_name" varchar,
  "category_id" int,
  "storage_area_id" int,
  "purchase_date" date,
  "purchase_price_id" int,
  "msrp_id" int,
  "residual_value_id" int,
  "parent_asset_id" int,
  "is_kit_root" bool,
  "is_attachment" bool,
  "serial_number" varchar,
  "inventory_number" int,
  "description" varchar,
  "is_available" bool,
  "online_item_page" varchar,
  "warranty_starts" date,
  "warranty_ends" date,
  "audit_info_id" int
);

CREATE TABLE "asset_flags" (
  "asset_id" int,
  "flag_id" int,
  "audit_info_id" int
);

CREATE TABLE "flags" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" varchar,
  "makes_unavailable" bool,
  "audit_info_id" int
);

CREATE TABLE "currencies" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "symbol" varchar,
  "iso_code" varchar,
  "audit_info_id" int
);

CREATE TABLE "financial_entries" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "currency_id" smallint,
  "amount" "decimal(10, 2)",
  "audit_info_id" int
);

CREATE TABLE "asset_location_logs" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "asset_id" int,
  "latitude" decimal(9,6),
  "longitude" decimal(9,6),
  "audit_info_id" int
);

CREATE TABLE "asset_file_attachments" (
  "asset_id" int,
  "attachment_id" int,
  "attachment_type" attachment_type,
  "audit_info_id" int
);

CREATE TABLE "file_attachments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "file_data" bytea,
  "file_url" varchar,
  "file_type" file_types,
  "file_category" file_categories,
  "size" image_size,
  "audit_info_id" int
);

CREATE TABLE "email_addersses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "email_adderss" varchar,
  "type" email_type,
  "is_verified" bool,
  "is_primary" bool,
  "is_shared" bool,
  "audit_info_id" int
);

CREATE TABLE "phone_numbers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "phone_type" phone_type,
  "country_code" smallint,
  "area_code" smallint,
  "phone_number" smallint,
  "extension" smallint,
  "is_verified" bool,
  "is_primary" bool,
  "audit_info_id" int
);

CREATE TABLE "user_settings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "currency_id" smallint,
  "time_format" varchar(5),
  "is_darkmode" bool,
  "audit_info_id" int
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "password_hash" varchar,
  "first_name" varchar,
  "middle_name" varchar,
  "last_name" varchar,
  "nickname" varchar,
  "nickname_prefered" bool,
  "last_login" timestamp,
  "audit_info_id" int
);

CREATE TABLE "user_file_attachments" (
  "user_id" int,
  "attachment_id" int,
  "attachment_type" attachment_type,
  "audit_info_id" int
);

CREATE TABLE "user_roles" (
  "user_id" int,
  "role_id" int,
  "audit_info_id" int
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" text,
  "audit_info_id" int
);

CREATE TABLE "permissions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" varchar,
  "audit_info_id" int
);

CREATE TABLE "role_permissions" (
  "role_id" int,
  "permission_id" int,
  "audit_info_id" int
);

CREATE TABLE "areas" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parent_area_id" int,
  "name" varchar,
  "latitude" decimal(9,6),
  "longitude" decimal(9,6),
  "address_id" int,
  "audit_info_id" int
);

CREATE TABLE "area_file_attachments" (
  "area_id" int,
  "attachment_id" int,
  "attachment_type" attachment_type,
  "audit_info_id" int
);

CREATE TABLE "addresses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" address_type,
  "street" varchar,
  "city" varchar,
  "state_id" smallint,
  "zip" varchar(10),
  "country_id" smallint,
  "audit_info_id" int
);

CREATE TABLE "countries" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" iso_country_codes,
  "intl_phone_code" smallint,
  "name" varchar
);

CREATE TABLE "timezones" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "identifier" timezones
);

CREATE TABLE "states" (
  "id" SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" state_codes,
  "name" state_names,
  "timezone_id" int,
  "country_id" smallint
);

COMMENT ON COLUMN "global_settings"."id" IS 'Primary key';

COMMENT ON COLUMN "global_settings"."default_currency_id" IS 'Foreign key to default currency';

COMMENT ON COLUMN "global_settings"."time_format_is_24h" IS 'Format of time ("12hr" or "24hr")';

COMMENT ON COLUMN "global_settings"."audit_info_id" IS 'Foreign key to audit information';

COMMENT ON COLUMN "audit_info"."id" IS 'Primary key';

COMMENT ON COLUMN "audit_info"."operation_type" IS 'Type of operation performed. Example: CREATE, UPDATE, DELETE, ARCHIVE';

COMMENT ON COLUMN "audit_info"."details" IS 'Extra details about the operation';

COMMENT ON COLUMN "audit_info"."created_by" IS 'Foreign key to user who created the record';

COMMENT ON COLUMN "audit_info"."created_at" IS 'Timestamp of creation';

COMMENT ON COLUMN "audit_info"."last_edited_by" IS 'Foreign key to last user who edited the record';

COMMENT ON COLUMN "audit_info"."last_edited_at" IS 'Timestamp of last edit';

COMMENT ON COLUMN "audit_info"."is_archived" IS 'Whether the record is archived';

COMMENT ON COLUMN "audit_info"."archived_at" IS 'Timestamp of when the record was archived';

COMMENT ON COLUMN "reservations"."id" IS 'Primary key';

COMMENT ON COLUMN "reservations"."reserved_for" IS 'Foreign key to user the reservation is for';

COMMENT ON COLUMN "reservations"."area_id" IS 'Foreign key to area of reservation';

COMMENT ON COLUMN "reservations"."planned_checkout_time" IS 'Planned time to check out';

COMMENT ON COLUMN "reservations"."planned_checkin_time" IS 'Planned time to check in';

COMMENT ON COLUMN "reservations"."checkout_time" IS 'Actual checkout time';

COMMENT ON COLUMN "reservations"."checkin_time" IS 'Actual check-in time';

COMMENT ON COLUMN "reservations"."is_indefinite" IS 'If the reservation is going to be indefinate';

COMMENT ON COLUMN "reservations"."audit_info_id" IS 'Foreign key to audit information';

COMMENT ON COLUMN "reservation_assets"."audit_info_id" IS 'Points audit table for history of changes.';

COMMENT ON COLUMN "scan_tags"."audit_info_id" IS 'Points audit table for history of changes.';

COMMENT ON COLUMN "comments"."parent_comment_id" IS 'For Nesting';

COMMENT ON COLUMN "comments"."audit_info_id" IS 'Points audit table for history of changes.';

COMMENT ON COLUMN "reactions"."user_id" IS 'The user who gave the reaction.';

COMMENT ON COLUMN "reactions"."comment_id" IS 'Which comment the reaction is for.';

COMMENT ON COLUMN "reactions"."reaction_type" IS 'For standard emoji reactions like "thumb_up", "smile", etc.';

COMMENT ON COLUMN "reactions"."audit_info_id" IS 'Points to audit table for history of changes.';

COMMENT ON COLUMN "categories"."parent_category_id" IS 'For Nesting';

COMMENT ON COLUMN "categories"."audit_info_id" IS 'Points audit table for history of changes.';

COMMENT ON COLUMN "custom_properties"."audit_info_id" IS 'Points audit table for history of changes.';

COMMENT ON COLUMN "asset_custom_properties"."value" IS 'The actual value associated with this asset for the given property';

COMMENT ON COLUMN "asset_custom_properties"."audit_info_id" IS 'Points audit table for history of changes.';

COMMENT ON COLUMN "assets"."id" IS 'Primary key';

COMMENT ON COLUMN "assets"."manufacturer" IS 'Brand/Manufacturer of the asset';

COMMENT ON COLUMN "assets"."model_number" IS 'Model number of the asset';

COMMENT ON COLUMN "assets"."model_name" IS 'Model name of the asset';

COMMENT ON COLUMN "assets"."category_id" IS 'Foreign key to category';

COMMENT ON COLUMN "assets"."storage_area_id" IS 'Foreign key to storage area';

COMMENT ON COLUMN "assets"."purchase_date" IS 'Purchase date of the asset';

COMMENT ON COLUMN "assets"."purchase_price_id" IS 'Foreign key to purchase price';

COMMENT ON COLUMN "assets"."msrp_id" IS 'Foreign key to manufacturer"s suggested retail price';

COMMENT ON COLUMN "assets"."residual_value_id" IS 'Foreign key to residual value of the asset';

COMMENT ON COLUMN "assets"."parent_asset_id" IS 'If part of a kit, reference to parent asset';

COMMENT ON COLUMN "assets"."is_kit_root" IS 'Indicates if the asset is the root of a kit';

COMMENT ON COLUMN "assets"."is_attachment" IS 'Indicates if the asset is an attachment';

COMMENT ON COLUMN "assets"."serial_number" IS 'Serial number of the asset';

COMMENT ON COLUMN "assets"."inventory_number" IS 'Inventory number of the asset';

COMMENT ON COLUMN "assets"."description" IS 'Description of the asset';

COMMENT ON COLUMN "assets"."is_available" IS 'Availability status of the asset';

COMMENT ON COLUMN "assets"."online_item_page" IS 'Link to the asset"s online page';

COMMENT ON COLUMN "assets"."warranty_starts" IS 'Start date of warranty for the asset';

COMMENT ON COLUMN "assets"."warranty_ends" IS 'End date of warranty for the asset';

COMMENT ON COLUMN "assets"."audit_info_id" IS 'Foreign key to audit information';

COMMENT ON COLUMN "asset_flags"."audit_info_id" IS 'Tracks when the flag was added to or removed from the asset';

COMMENT ON COLUMN "flags"."audit_info_id" IS 'Tracks when the flag was created, updated, or archived';

COMMENT ON COLUMN "currencies"."id" IS 'Primary key';

COMMENT ON COLUMN "currencies"."name" IS 'Currency name';

COMMENT ON COLUMN "currencies"."symbol" IS 'Currency symbol';

COMMENT ON COLUMN "currencies"."iso_code" IS 'Currency ISO code';

COMMENT ON COLUMN "currencies"."audit_info_id" IS 'Reference to audit info';

COMMENT ON COLUMN "financial_entries"."id" IS 'Primary key';

COMMENT ON COLUMN "financial_entries"."currency_id" IS 'Reference to currency';

COMMENT ON COLUMN "financial_entries"."amount" IS 'Monetary amount';

COMMENT ON COLUMN "financial_entries"."audit_info_id" IS 'Reference to audit info';

COMMENT ON TABLE "asset_location_logs" IS 'for GEO tracking';

COMMENT ON COLUMN "asset_location_logs"."audit_info_id" IS 'Points audit table for history of changes.';

COMMENT ON COLUMN "asset_file_attachments"."audit_info_id" IS 'Points audit table for history of changes.';

COMMENT ON COLUMN "file_attachments"."file_data" IS 'Binary data for the attachment';

COMMENT ON COLUMN "file_attachments"."file_url" IS 'URL for the attachment';

COMMENT ON COLUMN "file_attachments"."file_type" IS 'Type of the attachment (e.g., "image", "pdf", "doc")';

COMMENT ON COLUMN "file_attachments"."file_category" IS 'What kind of file is it? Media, document';

COMMENT ON COLUMN "file_attachments"."size" IS 'Size type for images';

COMMENT ON COLUMN "file_attachments"."audit_info_id" IS 'Points audit table for history of changes.';

COMMENT ON COLUMN "email_addersses"."audit_info_id" IS 'Points audit table for history of changes.';

COMMENT ON COLUMN "phone_numbers"."audit_info_id" IS 'Points audit table for history of changes.';

COMMENT ON COLUMN "user_settings"."currency_id" IS 'If null, fallback to global setting';

COMMENT ON COLUMN "user_settings"."time_format" IS 'If null, fallback to global setting';

COMMENT ON COLUMN "user_settings"."is_darkmode" IS 'Could also, be an enum for different themes?';

COMMENT ON COLUMN "user_settings"."audit_info_id" IS 'Points audit table for history of changes.';

COMMENT ON COLUMN "users"."id" IS 'Primary key';

COMMENT ON COLUMN "users"."password_hash" IS 'Hashed password for user';

COMMENT ON COLUMN "users"."first_name" IS 'First name of the user';

COMMENT ON COLUMN "users"."middle_name" IS 'Middle name of the user';

COMMENT ON COLUMN "users"."last_name" IS 'Last name of the user';

COMMENT ON COLUMN "users"."nickname" IS 'Option nickname of the user';

COMMENT ON COLUMN "users"."nickname_prefered" IS 'Do they prefer to go by their nickname?';

COMMENT ON COLUMN "users"."audit_info_id" IS 'Points audit table for history of changes.';

COMMENT ON COLUMN "user_file_attachments"."audit_info_id" IS 'Points audit table for history of changes.';

COMMENT ON COLUMN "user_roles"."user_id" IS 'Reference to users';

COMMENT ON COLUMN "user_roles"."role_id" IS 'Reference to roles';

COMMENT ON COLUMN "user_roles"."audit_info_id" IS 'Reference to audit info';

COMMENT ON COLUMN "roles"."id" IS 'Primary key';

COMMENT ON COLUMN "roles"."name" IS 'Role name';

COMMENT ON COLUMN "roles"."description" IS 'Description of the role';

COMMENT ON COLUMN "roles"."audit_info_id" IS 'Reference to audit info';

COMMENT ON COLUMN "permissions"."id" IS 'Primary key';

COMMENT ON COLUMN "permissions"."name" IS 'Permission name';

COMMENT ON COLUMN "permissions"."description" IS 'Permission description';

COMMENT ON COLUMN "permissions"."audit_info_id" IS 'Reference to audit info';

COMMENT ON COLUMN "role_permissions"."role_id" IS 'Reference to roles';

COMMENT ON COLUMN "role_permissions"."permission_id" IS 'Reference to permissions';

COMMENT ON COLUMN "role_permissions"."audit_info_id" IS 'Reference to audit info';

COMMENT ON TABLE "areas" IS 'This will represent different spatial areas that can contain assets. It can be nested to represent a hierarchy of areas, such as buildings, rooms, shelves, etc.';

COMMENT ON COLUMN "areas"."id" IS 'Primary key';

COMMENT ON COLUMN "areas"."parent_area_id" IS 'For nesting';

COMMENT ON COLUMN "areas"."name" IS 'Area name';

COMMENT ON COLUMN "areas"."latitude" IS 'GPS Latitude, optional';

COMMENT ON COLUMN "areas"."longitude" IS 'GPS Longitude, optional';

COMMENT ON COLUMN "areas"."address_id" IS 'If it has an address, what is it?';

COMMENT ON COLUMN "areas"."audit_info_id" IS 'Points audit table for history of changes.';

COMMENT ON COLUMN "area_file_attachments"."attachment_id" IS 'Changed from image_id';

COMMENT ON COLUMN "area_file_attachments"."audit_info_id" IS 'Points audit table for history of changes.';

COMMENT ON COLUMN "addresses"."audit_info_id" IS 'Points audit table for history of changes.';

COMMENT ON COLUMN "timezones"."identifier" IS 'Full Timezone Identifier';

ALTER TABLE "global_settings" ADD FOREIGN KEY ("default_currency_id") REFERENCES "currencies" ("id");

ALTER TABLE "global_settings" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "audit_info" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id");

ALTER TABLE "audit_info" ADD FOREIGN KEY ("last_edited_by") REFERENCES "users" ("id");

ALTER TABLE "reservations" ADD FOREIGN KEY ("reserved_for") REFERENCES "users" ("id");

ALTER TABLE "reservations" ADD FOREIGN KEY ("area_id") REFERENCES "areas" ("id");

ALTER TABLE "reservations" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "reservation_assets" ADD FOREIGN KEY ("reservation_id") REFERENCES "reservations" ("id");

ALTER TABLE "reservation_assets" ADD FOREIGN KEY ("asset_id") REFERENCES "assets" ("id");

ALTER TABLE "reservation_assets" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "scan_tags" ADD FOREIGN KEY ("asset_id") REFERENCES "assets" ("id");

ALTER TABLE "scan_tags" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("parent_comment_id") REFERENCES "comments" ("id");

ALTER TABLE "comments" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "reactions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "reactions" ADD FOREIGN KEY ("comment_id") REFERENCES "comments" ("id");

ALTER TABLE "reactions" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "categories" ADD FOREIGN KEY ("parent_category_id") REFERENCES "categories" ("id");

ALTER TABLE "categories" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "custom_properties" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "asset_custom_properties" ADD FOREIGN KEY ("asset_id") REFERENCES "assets" ("id");

ALTER TABLE "asset_custom_properties" ADD FOREIGN KEY ("property_id") REFERENCES "custom_properties" ("id");

ALTER TABLE "asset_custom_properties" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "assets" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "assets" ADD FOREIGN KEY ("storage_area_id") REFERENCES "areas" ("id");

ALTER TABLE "assets" ADD FOREIGN KEY ("purchase_price_id") REFERENCES "financial_entries" ("id");

ALTER TABLE "assets" ADD FOREIGN KEY ("msrp_id") REFERENCES "financial_entries" ("id");

ALTER TABLE "assets" ADD FOREIGN KEY ("residual_value_id") REFERENCES "financial_entries" ("id");

ALTER TABLE "assets" ADD FOREIGN KEY ("parent_asset_id") REFERENCES "assets" ("id");

ALTER TABLE "assets" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "asset_flags" ADD FOREIGN KEY ("asset_id") REFERENCES "assets" ("id");

ALTER TABLE "asset_flags" ADD FOREIGN KEY ("flag_id") REFERENCES "flags" ("id");

ALTER TABLE "asset_flags" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "flags" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "currencies" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "financial_entries" ADD FOREIGN KEY ("currency_id") REFERENCES "currencies" ("id");

ALTER TABLE "financial_entries" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "asset_location_logs" ADD FOREIGN KEY ("asset_id") REFERENCES "assets" ("id");

ALTER TABLE "asset_location_logs" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "asset_file_attachments" ADD FOREIGN KEY ("asset_id") REFERENCES "assets" ("id");

ALTER TABLE "asset_file_attachments" ADD FOREIGN KEY ("attachment_id") REFERENCES "file_attachments" ("id");

ALTER TABLE "asset_file_attachments" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "file_attachments" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "email_addersses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "email_addersses" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "phone_numbers" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "phone_numbers" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "user_settings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_settings" ADD FOREIGN KEY ("currency_id") REFERENCES "currencies" ("id");

ALTER TABLE "user_settings" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "user_file_attachments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_file_attachments" ADD FOREIGN KEY ("attachment_id") REFERENCES "file_attachments" ("id");

ALTER TABLE "user_file_attachments" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "roles" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "permissions" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "role_permissions" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id");

ALTER TABLE "role_permissions" ADD FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id");

ALTER TABLE "role_permissions" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "areas" ADD FOREIGN KEY ("parent_area_id") REFERENCES "areas" ("id");

ALTER TABLE "areas" ADD FOREIGN KEY ("address_id") REFERENCES "addresses" ("id");

ALTER TABLE "areas" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "area_file_attachments" ADD FOREIGN KEY ("area_id") REFERENCES "areas" ("id");

ALTER TABLE "area_file_attachments" ADD FOREIGN KEY ("attachment_id") REFERENCES "file_attachments" ("id");

ALTER TABLE "area_file_attachments" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "addresses" ADD FOREIGN KEY ("state_id") REFERENCES "states" ("id");

ALTER TABLE "addresses" ADD FOREIGN KEY ("country_id") REFERENCES "countries" ("id");

ALTER TABLE "addresses" ADD FOREIGN KEY ("audit_info_id") REFERENCES "audit_info" ("id");

ALTER TABLE "states" ADD FOREIGN KEY ("timezone_id") REFERENCES "timezones" ("id");

ALTER TABLE "states" ADD FOREIGN KEY ("country_id") REFERENCES "countries" ("id");
